---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-color
  labels:
    app: myapp-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      envFrom:
        - SecretRef:
          name: app-config
